### ISSUE TITLE
Exceptions not found/ installed

### ISSUE THREAD

**Issue by nyxxtra** [nyxxtra/UNVAPT#3]
Traceback (most recent call last):
  File "c:\Users\*****\Desktop\2.2\main.py", line 8, in <module>
    from docx import Document
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'

**Comment by nyxxtra** [comment]
**_pip install exceptions_** should fix this
